package com.zenlabs.msg.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A single SMS message within a conversation. The [trngId] is generated by the
 * app's TRNG module so every message carries a unique, verifiable identifier
 * independent of the auto-increment row id.
 */
@Entity(
    tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity = Conversation::class,
            parentColumns = ["id"],
            childColumns = ["conversationId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("conversationId"), Index("address"), Index("trngId", unique = true)]
)
data class Message(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val conversationId: Long,
    val address: String,
    val body: String,
    val timestamp: Long,
    val sentByMe: Boolean,
    val status: Int,           // PENDING, SENT, DELIVERED, FAILED
    val trngId: String,        // TRNG-derived unique id
    val trngKeyHex: String? = null // optional per-message nonce
) {
    companion object {
        const val STATUS_PENDING = 0
        const val STATUS_SENT = 1
        const val STATUS_DELIVERED = 2
        const val STATUS_FAILED = 3
    }
}
